### ISSUE TITLE
PIggyback on #916 -- CBZ internal files with no leading digits

### ISSUE THREAD

**Issue by armouredking** [9001/copyparty#983]
**Is your feature request related to a problem? Please describe.**
#916 provided the CBZ feature for viewing in browser, but doesn't sort internal information correctly if those files within the archive have no leading zeroes (i.e. 1,2,3,4,5,6,7,8,9,10,11... will become 1,10,11,12... when viewed)

**Describe the idea / solution you'd like**
Either automatically smart enough to figure out order, or an option in control panel to tell it to sort the files in a 'human read' fashion

**Describe any alternatives you've considered**
This is a feature-set of similar readers like Komga, but it would be nice to have in CopyParty

**Comment by Scotsguy** [comment]
Do you have an example of the filenames in a cbz which are incorrectly sorted because they expect natural sort order instead of lexicographic? I didn't think anyone would mess up a cbz that much

Also, does this file have the correct thumbnail? In particularly funky scenarios that might also not get th correct image

**Comment by armouredking** [comment]
> Do you have an example of the filenames in a cbz which are incorrectly sorted because they expect natural sort order instead of lexicographic? I didn't think anyone would mess up a cbz that much

I provided an example. Quite a few of my old CBZs have this arrangement, where they do not have leading zeroes in the content file names. This causes the sorting to be 1, 10, 11... 2, 20, 21... etc. Quite a few of my EPUB conversion files (where I extracted the images and made it a CBZ instead of an EPUB and didn't know better because I mostly had them as folders with files and viewed them in Windows Photo Viewer long before knowing about CBZs) are like this, too.

Any setup without leading zeroes tends to get sorted improperly by most software suites, but I know Komga can handle this issue. I think Kavita does too, but been a while since I tested that one. On my never-ending list of things to sort out.

> Also, does this file have the correct thumbnail? In particularly funky scenarios that might also not get th correct image

As for covers, that's less of an issue for me and not what this ticket is about. Quite a few older CBZs have covers that aren't labelled properly or are a few files in rather than being the first file (and aren't labelled) -- I can live with that. I'll eventually get around to fixing them (much like my Jellyfin library) but fixing all the files without leading zeroes is a lot more work than just adding/detailing cover images (especially since, with CopyParty, fixing a cover image doesn't even need editing the CBZ -- just gotta chuck a file in the folder and let that be the preview, and I already have a lot of those from Komga).

**Comment by Scotsguy** [comment]
> I provided an example. Quite a few of my old CBZs have this arrangement, where they do not have leading zeroes in the content file names. This causes the sorting to be 1, 10, 11... 2, 20, 21... etc. Quite a few of my EPUB conversion files (where I extracted the images and made it a CBZ instead of an EPUB and didn't know better because I mostly had them as folders with files and viewed them in Windows Photo Viewer long before knowing about CBZs) are like this, too.

Do you mean the files are named `1.jpg, 2.jpg, ..., 10.jpg, 11.jpg`?

Also, are any of the files in folders inside the CBZ?

I don't have any files that are like this, so I wouldn't be able to test this if I implemented it without asking you for specifics.


> Any setup without leading zeroes tends to get sorted improperly by most software suites, but I know Komga can handle this issue. I think Kavita does too, but been a while since I tested that one. On my never-ending list of things to sort out.

I'll check out what algorithm Komga and Kavita use for sort order, then.

**Comment by armouredking** [comment]
> Do you mean the files are named `1.jpg, 2.jpg, ..., 10.jpg, 11.jpg`?

The ones I was testing the issue with are setup like that, yes. JPG, PNG, and WEBP. They don't have leading zeroes in the file names; newer mangas I've tested that _do_ have them work just fine. There are some others I think I still have that have names from when they came from epubs and were divided by sections (i.e. a_long_name_here_###.jpg), but I'm not sure which ones those are anymore.

I checked my J-Novel Club manga files, though, and the current CopyParty setup seems to handle those fine (they have names like i-###.webp).
 
> Also, are any of the files in folders inside the CBZ?

No. I'm not aware of any CBZs that I have which are setup with internal folders -- I definitely did not keep the sectional formatting of the epubs (that was one of my reasons for ditching them, tbf -- epub files for manga is a crutch at the best of times), but I'm not sure I ran all of them through batch renamers back when I was first sorting out my library.
